---
# Role metadata

galaxy_info:
  author: Ansible
  description: Configure k3s API server OIDC integration with Keycloak
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - k3s
    - kubernetes
    - oidc
    - keycloak
    - rbac

dependencies:
  - role: keycloak-config
