---
# Role metadata

galaxy_info:
  author: Ansible
  description: Configure GitLab OIDC integration with Keycloak
  license: MIT
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - gitlab
    - oidc
    - keycloak
    - kubernetes
    - authentication

dependencies:
  - role: keycloak-config
