---
all:
  children:
    k3s_nodes:
      hosts:
        k3s-server:
          ansible_host: 10.10.1.70
          ansible_user: "{{ lookup('env', 'USER') }}"
          ansible_ssh_private_key_file: "~/.ssh/id_rsa"
          ansible_python_interpreter: /usr/bin/python3
